name: Docker Image CI

on:
  push:
    branches: [ "beta", "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository source
      uses: actions/checkout@v4

    - name: Set up Docker Buildx engine
      uses: docker/setup-buildx-action@v3

    - name: Log into Docker Hub account
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata for tracking
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: nado42/python-ha-learning-thermostat
        tags: |
          type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
          type=raw,value=beta,enable=${{ github.ref == 'refs/heads/beta' }}

    - name: Build and push production image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
